spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
